version: 2
updates:
- package-ecosystem: "pip"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: "develop"    
  reviewers:
    - "danielcuthbert"
    - "javixeneize"
    - "pealtrufo"
    - "emilejq"
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"
  target-branch: "develop"    
  reviewers:
    - "danielcuthbert"
    - "javixeneize"
    - "pealtrufo"
    - "emilejq"
